### ISSUE TITLE
supporting multiple nest:

### ISSUE THREAD

**Issue by yan7109** [huei90/i18n-generator#5]
i18n=> | en | zh_TW | cn
global=> 
local=> 
we | we | 我們 | 我们
<= 
local2=>
they | they  | 他們 | 他们
<=
<=
should result in 
{"global":{"local":{"we":"we"},"local2":{"they":"they"}}}
not: 
{"global":{"local":{"we":"we"}},"local2":{"they":"they"}}

**Comment by yan7109** [comment]
simply change i18n-generator.js line 111 from
```variable.nestObject = []; variable.nestObject.pop();```

**Comment by huei90** [comment]
@yan7109 Thanks for your comment
https://github.com/huei90/i18n-generator/pull/3#issuecomment-120782088

**Comment by yan7109** [comment]
thanks, great tool otherwise! @huei90

**Comment by huei90** [comment]
:smile: Thanks.
Please tell me if there is something to improve.
